name: Follow Compilation.md on Mac

on:
  push:
    branches: ['*']
    tags: 
  pull_request:
  release:
    types: ['created']

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Compiling from source on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Homebrew Octave
      run: |
           brew update
           brew install octave
           octave --no-gui --no-window-system --eval "ver" || true
           octave --no-gui --no-window-system --eval "pkg list" || true
           octave --no-gui --no-window-system --eval "pkg install -forge control signal" || true
           octave --no-gui --no-window-system --eval "javaclasspath" || true
           false
    - name: Install macOS prerequesites via Homebrew
      run: |
           uname -a
           brew update
           brew install libsndfile
           brew install portaudio
           brew install liblo
           brew install eigen
    - name: Install macOS prerequisites via pkg installers
      run: |
           wget https://github.com/jackaudio/jack2-releases/releases/download/v1.9.20/jack2-macOS-intel-v1.9.20.tar.gz
           tar xf jack2-macOS-intel-v1.9.20.tar.gz
           sudo installer -pkg $PWD/jack2-osx-1.9.20.pkg -target /
           rm -r jack2-macOS-intel-v1.9.20.tar.gz jack2-osx-1.9.20.pkg QjackCtl.app
    - name: Configure and build openMHA
      run: |
           ./configure
           make -j 3
    - name: Installation of self-compiled openMHA
      run: |
           make -j 3 install
           source bin/thismha.sh && mha '?' cmd=quit
    - name: unit-tests
      run: |
           brew install boost
           make -j 4 unit-tests
    - name: system tests
      run: |
           brew install octave
           ./configure
           make -j 2 test
